### ISSUE TITLE
aiohttp leaks ContextVar changes despite ctx = context_copy(); ctx.run()

### ISSUE THREAD

**Issue by mistotebe** [MagicStack/pep567#13]
Potentially related to #2.

Take the following code:
```python3
#!/usr/bin/env python3

from aiohttp import web
import contextvars
import functools

variable = contextvars.ContextVar('variable')
variable.set(False)


def with_context(f):
    @functools.wraps(f)
    def wrapper(*args, **kwargs):
        ctx = contextvars.copy_context()
        return ctx.run(f, *args, **kwargs)
    return wrapper


@with_context
async def handler(request):
    before = variable.get()

    if request.method == 'GET':
        variable.set(True)

    after = variable.get()
    return web.json_response({'before': before, 'after': after})


def main():
    app = web.Application()

    app.router.add_get('/action', handler)
    app.router.add_post('/action', handler)

    web.run_app(app, host='localhost', port=12345)

if __name__ == '__main__':
    main()

```

In 3.7 contextvars (stdlib implementation), GET requests do not interfere with `variable` (even if the decorator is not present). In 3.6 with contextvars 2.4, the change to `variable` leaks out, regardless of whether `handler` is decorated.

Why does `ctx.run()` not protect the top-level context from changes?

Is there a workaround?

**Comment by 1st1** [comment]
Yeah, this seems to be related to #2. :( 

I'll be frank -- there are no plans to further enhance this package. It exists solely for the purpose of defining contextvars APIs for other packages like trio and uvloop.  I'd suggest to start using the latest 3.7/3.8 Python instead of relying on this package.

**Comment by mistotebe** [comment]
I was hoping to use this package as a backport of contextvars to 3.6 until we can get rid of RHEL7.

Do you have any ideas what is broken, so I could take a stab at fixing it?

**Comment by 1st1** [comment]
Nothing is broken, but the integration with asyncio is missing. And it's a huge one requiring a lot of work.
